# SETTINGS FOR MEG REPLAY TASK
number training trials:
  n_training_trials: 8  # Number of trials in the training session
  n_test_trials: 8  # Number of trials in the test session
  n_test_successes: 6  # Number of consecutive successes required to pass the test phase
durations:
  start_duration: 4  # Planning phase duration
  start_duration_test: 4  # Planning phase duration - test phase
  pre_move_duration: 1  # 'Get ready to enter moves' duration
  move_entering_duration_initial: 10  # Initial time given to enter moves in test phase, this reduces gradually
  move_entering_reduction_length: 40 # Number of trials before move entering duration reaches the true duration
  move_entering_duration: 6  # Time given to enter moves
  pre_move_fixation_duration: 0.5 # Fixation before moves are shown
  move_durations: !!python/list [1.6, 1.6, 1.6, 3]  # Duration moves are shown for
  outcome_only_text_duration: 2  #
  outcome_only_duration: 3  #
  rest_duration: 2  # Rest after outcome
  rest_duration_test: 2  # Rest after outcome
  shock_delay: 0.8  # Delay before shocks are given following the shock image
  shock_symbol_delay: 1 # Delay before showing shock image
  n_moves: 3  # Number of moves subjects make
  n_shocks: 5  # Number of shocks in each shock train
  trials_per_block: 20 #
MEG_durations:
  start_duration: 6  # Planning phase duration
  start_duration_test: 6  # Planning phase duration - test phase
  pre_move_duration: 0.8  # 'Get ready to enter moves' duration
  move_entering_duration_initial: 10  # Initial time given to enter moves in test phase, this reduces gradually
  move_entering_reduction_length: 40 # Number of trials before move entering duration reaches the true duration
  move_entering_duration: 6  # Time given to enter moves
  pre_move_fixation_duration: 0.5 # Fixation before moves are shown
  move_durations: !!python/list [0.8, 0.8, 0.8, 3]  # Duration moves are shown for
  outcome_only_text_duration: 2  #
  outcome_only_duration: 3  #
  rest_duration: 6  # Rest after outcome
  rest_duration_test: 2  # Rest after outcome - test phase
  shock_delay: 0.8  # Delay before shocks are given following the shock image
  shock_symbol_delay: 1 # Delay before showing shock image
  n_moves: 3  # Number of moves subjects make
  n_shocks: 0  # Number of shocks in each shock train
  trials_per_block: 20
directories:
  saved_data: 'Data/behavioural/'
  stimuli_path: 'Stimuli'
  arrow_path: 'Stimuli/Arrows'
  matrix: 'Task_information/transition_matrix.txt'
  trial_info: 'Task_information/trial_info.csv'
  trial_info_test: 'Task_information/trial_info.csv'
  main_instructions: 'Instructions/instructions.txt'
  training_instructions: 'Instructions/training_instructions.txt'
  task_instructions: 'Instructions/task_instructions.txt'
  test_instructions: 'Instructions/test_instructions.txt'
filenames:
  save_prefix: 'replay_task_behavioural'
response keys:
  response_keys: ['1', '2', '3', '4']
  response_phases: [0, 0, 1, 1, 2, 2]
image sizes:
  size_image_size: !!python/tuple [6, 6]  # Size of the state image stimuli
  size_outcome_image: !!python/tuple [2, 3]  #
  size_outcome_image_noshock: !!python/tuple [3, 3]  #
  size_display_image: !!python/tuple [11, 11]  #
  size_arrow_display: !!python/tuple [2, 3]  # Size of the arrow stimuli
  state_selection_spacing: 6
  size_selection_image: !!python/tuple [6, 6]
stimuli:
  shock: 'Stimuli/shock.png'
  noshock: 'Stimuli/noshock.png'
fonts:
  font_path: 'fonts/OpenSans-Regular.ttf'
  font_name: 'Open Sans'
triggers:
  rest: 4
  planning: 8
  move_entering: 100
  outcome_only_outcome: 84
  outcome_only_warning: 80
  shock_outcome: 12
  no_shock_outcome: 16
  state_trigger_start: 20  # initial state trigger ID



